### ISSUE TITLE
Add Github Actions!

### ISSUE THREAD

**Issue by kitarp29** [GDSC-DSI/api#21]
We need to implement some basic checks on each PR that is made to the repo

**Comment by RishiKumarRay** [comment]
I will do this assign me

**Comment by kitarp29** [comment]
make a list of basic NodeJS Github Actions
Post them over here
I will write more custom actions later myself!
All the best

**Comment by RishiKumarRay** [comment]
![Screenshot from 2022-01-20 11-00-03](https://user-images.githubusercontent.com/87641376/150279556-94ce9907-fcde-475d-b4e9-91c80159e562.png)
checkout this @kitarp29 i have tried and tested this its a basic CI , If you approve i will raise PR for it

**Comment by RishiKumarRay** [comment]
@kitarp29 also there are no test present so we can remove it and we will simply have npm ci and npm build

**Comment by kitarp29** [comment]
Yes @RishiKumarRay Remove the test for now.
I will write unit tests in the future.
If it works for you, go ahead make a PR.

**Comment by RishiKumarRay** [comment]
@kitarp29 please review pr #22

**Comment by kitarp29** [comment]
Merged!
Congrats @RishiKumarRay 
GG 🔥
